# Application Name
spring.application.name=coursemanagement

# MySQL Database
spring.datasource.url=jdbc:mysql://100.112.108.20:3306/coursemanagement
spring.datasource.username=Thor
spring.datasource.password=Spring@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect