name: Test Tailscale + SSH

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:ci

      - name: Check Tailscale
        run: |
          tailscale status

      - name: Test SSH port
        run: |
          tailscale nc 100.112.108.20 22

      - name: Test SSH login
        uses: appleboy/ssh-action@v1
        with:
          host: 100.112.108.20
          username: deploy
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "SSH connection successful"
            whoami
            hostname
            pwd
